language: python

dist: bionic

sudo: required

os:
  - linux

addons:
  apt:
    packages:
      - python3
      - fakeroot

script:
  - deb/make_debs.sh

before_deploy:
  - export RELEASE_PKG_FILE=$(ls deb/*.deb)

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
