language: python

dist: bionic

sudo: required

os:
  - linux

addons:
  apt:
    packages:
      - python3
      - fakeroot

script:
  - deb/make_debs.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "deb/desnapper.deb"
    - "deb/diff-match-patch.deb"
    - "deb/sxsdiff.deb"
  skip_cleanup: true
  on:
    tags: true
