# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/windows/DiffWindow/DiffWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiffWindow(object):
    def setupUi(self, DiffWindow):
        DiffWindow.setObjectName("DiffWindow")
        DiffWindow.resize(831, 578)
        self.verticalLayout = QtWidgets.QVBoxLayout(DiffWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DiffWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.firstSnapshotComboBox = QtWidgets.QComboBox(DiffWindow)
        self.firstSnapshotComboBox.setObjectName("firstSnapshotComboBox")
        self.horizontalLayout.addWidget(self.firstSnapshotComboBox)
        self.label_2 = QtWidgets.QLabel(DiffWindow)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.secondSnapshotComboBox = QtWidgets.QComboBox(DiffWindow)
        self.secondSnapshotComboBox.setObjectName("secondSnapshotComboBox")
        self.horizontalLayout.addWidget(self.secondSnapshotComboBox)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comparePushButton = QtWidgets.QPushButton(DiffWindow)
        self.comparePushButton.setObjectName("comparePushButton")
        self.horizontalLayout.addWidget(self.comparePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(DiffWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pathsTreeWidget = QtWidgets.QTreeWidget(self.splitter)
        self.pathsTreeWidget.setObjectName("pathsTreeWidget")
        self.fileWidget = QtWidgets.QWidget(self.splitter)
        self.fileWidget.setObjectName("fileWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.fileWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.diffWidget = DiffWidget(self.fileWidget)
        self.diffWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diffWidget.sizePolicy().hasHeightForWidth())
        self.diffWidget.setSizePolicy(sizePolicy)
        self.diffWidget.setObjectName("diffWidget")
        self.gridLayout.addWidget(self.diffWidget, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.changedLabel = QtWidgets.QLabel(self.fileWidget)
        self.changedLabel.setText("")
        self.changedLabel.setObjectName("changedLabel")
        self.gridLayout.addWidget(self.changedLabel, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.fileWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.forceDiffWidget = QtWidgets.QWidget(self.fileWidget)
        self.forceDiffWidget.setObjectName("forceDiffWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.forceDiffWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.forceDiffWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.forceDiffPushButton = QtWidgets.QPushButton(self.forceDiffWidget)
        self.forceDiffPushButton.setObjectName("forceDiffPushButton")
        self.horizontalLayout_3.addWidget(self.forceDiffPushButton)
        self.gridLayout.addWidget(self.forceDiffWidget, 2, 0, 1, 3)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(1, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.undoPushButton = QtWidgets.QPushButton(DiffWindow)
        self.undoPushButton.setObjectName("undoPushButton")
        self.horizontalLayout_2.addWidget(self.undoPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DiffWindow)
        QtCore.QMetaObject.connectSlotsByName(DiffWindow)
        DiffWindow.setTabOrder(self.firstSnapshotComboBox, self.secondSnapshotComboBox)
        DiffWindow.setTabOrder(self.secondSnapshotComboBox, self.comparePushButton)
        DiffWindow.setTabOrder(self.comparePushButton, self.pathsTreeWidget)
        DiffWindow.setTabOrder(self.pathsTreeWidget, self.forceDiffPushButton)
        DiffWindow.setTabOrder(self.forceDiffPushButton, self.undoPushButton)

    def retranslateUi(self, DiffWindow):
        _translate = QtCore.QCoreApplication.translate
        DiffWindow.setWindowTitle(_translate("DiffWindow", "Compare snapshots"))
        self.label.setText(_translate("DiffWindow", "Compare"))
        self.label_2.setText(_translate("DiffWindow", "with"))
        self.comparePushButton.setText(_translate("DiffWindow", "Compare"))
        self.pathsTreeWidget.headerItem().setText(0, _translate("DiffWindow", "File system"))
        self.label_3.setText(_translate("DiffWindow", "Has been changed:"))
        self.label_4.setText(_translate("DiffWindow", "File is long for diff"))
        self.forceDiffPushButton.setText(_translate("DiffWindow", "Force diff"))
        self.undoPushButton.setText(_translate("DiffWindow", "Undo selected files"))
from widgets.DiffWidget import DiffWidget
