# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ConfigSettingsWidget/ConfigSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigSettingsWidget(object):
    def setupUi(self, ConfigSettingsWidget):
        ConfigSettingsWidget.setObjectName("ConfigSettingsWidget")
        ConfigSettingsWidget.resize(484, 468)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigSettingsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsTabWidget = QtWidgets.QTabWidget(ConfigSettingsWidget)
        self.settingsTabWidget.setObjectName("settingsTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.timelineCreateCheckBox = QtWidgets.QCheckBox(self.tab)
        self.timelineCreateCheckBox.setObjectName("timelineCreateCheckBox")
        self.gridLayout_7.addWidget(self.timelineCreateCheckBox, 2, 0, 1, 1)
        self.backgruondComparisonCheckBox = QtWidgets.QCheckBox(self.tab)
        self.backgruondComparisonCheckBox.setChecked(True)
        self.backgruondComparisonCheckBox.setObjectName("backgruondComparisonCheckBox")
        self.gridLayout_7.addWidget(self.backgruondComparisonCheckBox, 3, 0, 1, 2)
        self.permGroupBox = QtWidgets.QGroupBox(self.tab)
        self.permGroupBox.setCheckable(False)
        self.permGroupBox.setChecked(False)
        self.permGroupBox.setObjectName("permGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.permGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.permGroupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.permGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.allowUsersListWidget = CheckableListWidget(self.permGroupBox)
        self.allowUsersListWidget.setObjectName("allowUsersListWidget")
        self.gridLayout_2.addWidget(self.allowUsersListWidget, 1, 0, 1, 2)
        self.allowGroupsListWidget = CheckableListWidget(self.permGroupBox)
        self.allowGroupsListWidget.setObjectName("allowGroupsListWidget")
        self.gridLayout_2.addWidget(self.allowGroupsListWidget, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.syncAclCheckBox = QtWidgets.QCheckBox(self.permGroupBox)
        self.syncAclCheckBox.setObjectName("syncAclCheckBox")
        self.horizontalLayout_4.addWidget(self.syncAclCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 3)
        self.gridLayout_7.addWidget(self.permGroupBox, 0, 0, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.settingsTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.numberCleanupGroupBox = QtWidgets.QGroupBox(self.tab_2)
        self.numberCleanupGroupBox.setCheckable(True)
        self.numberCleanupGroupBox.setChecked(False)
        self.numberCleanupGroupBox.setObjectName("numberCleanupGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.numberCleanupGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.numberCleanupGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.numberCleanupGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.numberMinAgeSpinBox = QtWidgets.QSpinBox(self.numberCleanupGroupBox)
        self.numberMinAgeSpinBox.setMaximum(2147483647)
        self.numberMinAgeSpinBox.setProperty("value", 1800)
        self.numberMinAgeSpinBox.setObjectName("numberMinAgeSpinBox")
        self.gridLayout.addWidget(self.numberMinAgeSpinBox, 0, 1, 1, 1)
        self.numberLimitSpinBox = RangeSpinBox(self.numberCleanupGroupBox)
        self.numberLimitSpinBox.setObjectName("numberLimitSpinBox")
        self.gridLayout.addWidget(self.numberLimitSpinBox, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.numberCleanupGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.numberLimitImportantSpinBox = RangeSpinBox(self.numberCleanupGroupBox)
        self.numberLimitImportantSpinBox.setObjectName("numberLimitImportantSpinBox")
        self.gridLayout.addWidget(self.numberLimitImportantSpinBox, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.numberCleanupGroupBox)
        self.timelineCleanupGroupBox = QtWidgets.QGroupBox(self.tab_2)
        self.timelineCleanupGroupBox.setCheckable(True)
        self.timelineCleanupGroupBox.setChecked(False)
        self.timelineCleanupGroupBox.setObjectName("timelineCleanupGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.timelineCleanupGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.timelineCleanupGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 2, 0, 1, 1)
        self.timelineMinAgeSpinBox = QtWidgets.QSpinBox(self.timelineCleanupGroupBox)
        self.timelineMinAgeSpinBox.setMaximum(2147483647)
        self.timelineMinAgeSpinBox.setProperty("value", 1800)
        self.timelineMinAgeSpinBox.setObjectName("timelineMinAgeSpinBox")
        self.gridLayout_8.addWidget(self.timelineMinAgeSpinBox, 0, 1, 1, 1)
        self.timelineLimitMonthlySpinBox = RangeSpinBox(self.timelineCleanupGroupBox)
        self.timelineLimitMonthlySpinBox.setProperty("value", 10)
        self.timelineLimitMonthlySpinBox.setObjectName("timelineLimitMonthlySpinBox")
        self.gridLayout_8.addWidget(self.timelineLimitMonthlySpinBox, 4, 1, 1, 1)
        self.timelineLimitYearlySpinBox = RangeSpinBox(self.timelineCleanupGroupBox)
        self.timelineLimitYearlySpinBox.setProperty("value", 10)
        self.timelineLimitYearlySpinBox.setObjectName("timelineLimitYearlySpinBox")
        self.gridLayout_8.addWidget(self.timelineLimitYearlySpinBox, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.timelineCleanupGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.timelineCleanupGroupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.timelineCleanupGroupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 3, 0, 1, 1)
        self.timelineLimitWeeklySpinBox = RangeSpinBox(self.timelineCleanupGroupBox)
        self.timelineLimitWeeklySpinBox.setObjectName("timelineLimitWeeklySpinBox")
        self.gridLayout_8.addWidget(self.timelineLimitWeeklySpinBox, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.timelineCleanupGroupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 4, 0, 1, 1)
        self.timelineLimitHourlySpinBox = RangeSpinBox(self.timelineCleanupGroupBox)
        self.timelineLimitHourlySpinBox.setObjectName("timelineLimitHourlySpinBox")
        self.gridLayout_8.addWidget(self.timelineLimitHourlySpinBox, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.timelineCleanupGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 1, 0, 1, 1)
        self.timelineLimitDailySpinBox = RangeSpinBox(self.timelineCleanupGroupBox)
        self.timelineLimitDailySpinBox.setObjectName("timelineLimitDailySpinBox")
        self.gridLayout_8.addWidget(self.timelineLimitDailySpinBox, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.timelineCleanupGroupBox)
        self.emptyPrePostClenupGroupBox = QtWidgets.QGroupBox(self.tab_2)
        self.emptyPrePostClenupGroupBox.setCheckable(True)
        self.emptyPrePostClenupGroupBox.setChecked(False)
        self.emptyPrePostClenupGroupBox.setObjectName("emptyPrePostClenupGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.emptyPrePostClenupGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.emptyPrePostClenupGroupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.emptyPrePostMinAgeSpinBox = QtWidgets.QSpinBox(self.emptyPrePostClenupGroupBox)
        self.emptyPrePostMinAgeSpinBox.setMaximum(2147483647)
        self.emptyPrePostMinAgeSpinBox.setProperty("value", 1800)
        self.emptyPrePostMinAgeSpinBox.setObjectName("emptyPrePostMinAgeSpinBox")
        self.horizontalLayout.addWidget(self.emptyPrePostMinAgeSpinBox)
        self.verticalLayout_2.addWidget(self.emptyPrePostClenupGroupBox)
        self.settingsTabWidget.addTab(self.tab_2, "")
        self.btrfsTab = QtWidgets.QWidget()
        self.btrfsTab.setObjectName("btrfsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.btrfsTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.btrfsTab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.spaceLimitSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.spaceLimitSpinBox.setMaximum(100)
        self.spaceLimitSpinBox.setProperty("value", 50)
        self.spaceLimitSpinBox.setObjectName("spaceLimitSpinBox")
        self.horizontalLayout_3.addWidget(self.spaceLimitSpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.btrfsTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qgroupComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.qgroupComboBox.setObjectName("qgroupComboBox")
        self.qgroupComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.qgroupComboBox)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.settingsTabWidget.addTab(self.btrfsTab, "")
        self.verticalLayout.addWidget(self.settingsTabWidget)

        self.retranslateUi(ConfigSettingsWidget)
        self.settingsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigSettingsWidget)
        ConfigSettingsWidget.setTabOrder(self.settingsTabWidget, self.permGroupBox)
        ConfigSettingsWidget.setTabOrder(self.permGroupBox, self.allowUsersListWidget)
        ConfigSettingsWidget.setTabOrder(self.allowUsersListWidget, self.allowGroupsListWidget)
        ConfigSettingsWidget.setTabOrder(self.allowGroupsListWidget, self.timelineCreateCheckBox)
        ConfigSettingsWidget.setTabOrder(self.timelineCreateCheckBox, self.backgruondComparisonCheckBox)
        ConfigSettingsWidget.setTabOrder(self.backgruondComparisonCheckBox, self.numberCleanupGroupBox)
        ConfigSettingsWidget.setTabOrder(self.numberCleanupGroupBox, self.numberMinAgeSpinBox)
        ConfigSettingsWidget.setTabOrder(self.numberMinAgeSpinBox, self.timelineCleanupGroupBox)
        ConfigSettingsWidget.setTabOrder(self.timelineCleanupGroupBox, self.timelineMinAgeSpinBox)
        ConfigSettingsWidget.setTabOrder(self.timelineMinAgeSpinBox, self.emptyPrePostClenupGroupBox)
        ConfigSettingsWidget.setTabOrder(self.emptyPrePostClenupGroupBox, self.emptyPrePostMinAgeSpinBox)
        ConfigSettingsWidget.setTabOrder(self.emptyPrePostMinAgeSpinBox, self.qgroupComboBox)
        ConfigSettingsWidget.setTabOrder(self.qgroupComboBox, self.spaceLimitSpinBox)

    def retranslateUi(self, ConfigSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        self.timelineCreateCheckBox.setText(_translate("ConfigSettingsWidget", "Enable hourly snapshots"))
        self.backgruondComparisonCheckBox.setText(_translate("ConfigSettingsWidget", "Enable background compare pre and post snapshots after creation"))
        self.permGroupBox.setTitle(_translate("ConfigSettingsWidget", "Users and groups allowed tp operate with config"))
        self.label.setText(_translate("ConfigSettingsWidget", "Users"))
        self.label_2.setText(_translate("ConfigSettingsWidget", "Groups"))
        self.syncAclCheckBox.setText(_translate("ConfigSettingsWidget", "Sync users and groups to ACL for snapshot folder"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.tab), _translate("ConfigSettingsWidget", "General"))
        self.numberCleanupGroupBox.setTitle(_translate("ConfigSettingsWidget", "Enable number cleanup algorithm"))
        self.label_7.setText(_translate("ConfigSettingsWidget", "How many snapshots should keep"))
        self.label_6.setText(_translate("ConfigSettingsWidget", "Minimal age for snapshots to be deleted"))
        self.label_8.setText(_translate("ConfigSettingsWidget", "How many important snapshots should keep"))
        self.timelineCleanupGroupBox.setTitle(_translate("ConfigSettingsWidget", "Enable timeline cleanup algorithm"))
        self.label_5.setText(_translate("ConfigSettingsWidget", "How many daily snapshots should keep"))
        self.label_9.setText(_translate("ConfigSettingsWidget", "Minimal age for snapshots to be deleted"))
        self.label_14.setText(_translate("ConfigSettingsWidget", "How many yearly snapshots should keep"))
        self.label_11.setText(_translate("ConfigSettingsWidget", "How many weekly snapshots should keep"))
        self.label_12.setText(_translate("ConfigSettingsWidget", "How many monthly snapshots should keep"))
        self.label_10.setText(_translate("ConfigSettingsWidget", "How many hourly snapshots should keep"))
        self.emptyPrePostClenupGroupBox.setTitle(_translate("ConfigSettingsWidget", "Enable the empty-pre-post cleanup algorithm"))
        self.label_13.setText(_translate("ConfigSettingsWidget", "Minimal age for snapshots to be deleted"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.tab_2), _translate("ConfigSettingsWidget", "Cleanup"))
        self.groupBox_6.setTitle(_translate("ConfigSettingsWidget", "Limit for the fraction of the filesystems space the snapshots should use"))
        self.spaceLimitSpinBox.setSuffix(_translate("ConfigSettingsWidget", "%"))
        self.groupBox_2.setTitle(_translate("ConfigSettingsWidget", "The btrfs quota group"))
        self.qgroupComboBox.setItemText(0, _translate("ConfigSettingsWidget", "None"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.btrfsTab), _translate("ConfigSettingsWidget", "btrfs"))
from widgets.CheckableListWidget import CheckableListWidget
from widgets.RangeSpinBox import RangeSpinBox
