# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/windows/CreateSnapshotWindow/CreateSnapshotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateSnapshotWindow(object):
    def setupUi(self, CreateSnapshotWindow):
        CreateSnapshotWindow.setObjectName("CreateSnapshotWindow")
        CreateSnapshotWindow.resize(458, 340)
        CreateSnapshotWindow.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(CreateSnapshotWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(CreateSnapshotWindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(CreateSnapshotWindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(CreateSnapshotWindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.snapshotTypeComboBox = QtWidgets.QComboBox(CreateSnapshotWindow)
        self.snapshotTypeComboBox.setObjectName("snapshotTypeComboBox")
        self.snapshotTypeComboBox.addItem("")
        self.snapshotTypeComboBox.addItem("")
        self.snapshotTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.snapshotTypeComboBox, 1, 0, 1, 1)
        self.basedOnComboBox = QtWidgets.QComboBox(CreateSnapshotWindow)
        self.basedOnComboBox.setObjectName("basedOnComboBox")
        self.gridLayout.addWidget(self.basedOnComboBox, 1, 1, 1, 1)
        self.cleanupTypeComboBox = QtWidgets.QComboBox(CreateSnapshotWindow)
        self.cleanupTypeComboBox.setObjectName("cleanupTypeComboBox")
        self.cleanupTypeComboBox.addItem("")
        self.cleanupTypeComboBox.addItem("")
        self.cleanupTypeComboBox.addItem("")
        self.cleanupTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.cleanupTypeComboBox, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(CreateSnapshotWindow)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addPushButton = QtWidgets.QPushButton(CreateSnapshotWindow)
        self.addPushButton.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.addPushButton.setIcon(icon)
        self.addPushButton.setFlat(True)
        self.addPushButton.setObjectName("addPushButton")
        self.horizontalLayout.addWidget(self.addPushButton)
        self.removePushButton = QtWidgets.QPushButton(CreateSnapshotWindow)
        self.removePushButton.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.removePushButton.setIcon(icon)
        self.removePushButton.setFlat(True)
        self.removePushButton.setObjectName("removePushButton")
        self.horizontalLayout.addWidget(self.removePushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.descriptionLineEdit = QtWidgets.QLineEdit(CreateSnapshotWindow)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.gridLayout.addWidget(self.descriptionLineEdit, 2, 0, 1, 5)
        self.userDataTableWidget = QtWidgets.QTableWidget(CreateSnapshotWindow)
        self.userDataTableWidget.setObjectName("userDataTableWidget")
        self.userDataTableWidget.setColumnCount(2)
        self.userDataTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.userDataTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.userDataTableWidget.setHorizontalHeaderItem(1, item)
        self.userDataTableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.userDataTableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.userDataTableWidget, 4, 0, 1, 5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.createPushButton = QtWidgets.QPushButton(CreateSnapshotWindow)
        icon = QtGui.QIcon.fromTheme("dialog-ok")
        self.createPushButton.setIcon(icon)
        self.createPushButton.setObjectName("createPushButton")
        self.horizontalLayout_2.addWidget(self.createPushButton)
        self.pushButton_2 = QtWidgets.QPushButton(CreateSnapshotWindow)
        icon = QtGui.QIcon.fromTheme("dialog-cancel")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 2, 1, 3)
        self.readOnlyCheckBox = QtWidgets.QCheckBox(CreateSnapshotWindow)
        self.readOnlyCheckBox.setObjectName("readOnlyCheckBox")
        self.gridLayout.addWidget(self.readOnlyCheckBox, 1, 3, 1, 1)

        self.retranslateUi(CreateSnapshotWindow)
        self.pushButton_2.clicked.connect(CreateSnapshotWindow.close)
        QtCore.QMetaObject.connectSlotsByName(CreateSnapshotWindow)
        CreateSnapshotWindow.setTabOrder(self.snapshotTypeComboBox, self.basedOnComboBox)
        CreateSnapshotWindow.setTabOrder(self.basedOnComboBox, self.cleanupTypeComboBox)
        CreateSnapshotWindow.setTabOrder(self.cleanupTypeComboBox, self.readOnlyCheckBox)
        CreateSnapshotWindow.setTabOrder(self.readOnlyCheckBox, self.descriptionLineEdit)

    def retranslateUi(self, CreateSnapshotWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateSnapshotWindow.setWindowTitle(_translate("CreateSnapshotWindow", "Create snapshot"))
        self.label.setText(_translate("CreateSnapshotWindow", "Snapshot type"))
        self.label_2.setText(_translate("CreateSnapshotWindow", "Based on snapshot"))
        self.label_3.setText(_translate("CreateSnapshotWindow", "Cleanup type"))
        self.snapshotTypeComboBox.setItemText(0, _translate("CreateSnapshotWindow", "Single"))
        self.snapshotTypeComboBox.setItemText(1, _translate("CreateSnapshotWindow", "Pre"))
        self.snapshotTypeComboBox.setItemText(2, _translate("CreateSnapshotWindow", "Post"))
        self.cleanupTypeComboBox.setItemText(0, _translate("CreateSnapshotWindow", "None"))
        self.cleanupTypeComboBox.setItemText(1, _translate("CreateSnapshotWindow", "Number"))
        self.cleanupTypeComboBox.setItemText(2, _translate("CreateSnapshotWindow", "Timeline"))
        self.cleanupTypeComboBox.setItemText(3, _translate("CreateSnapshotWindow", "Empty pre post"))
        self.label_4.setText(_translate("CreateSnapshotWindow", "User data"))
        self.descriptionLineEdit.setPlaceholderText(_translate("CreateSnapshotWindow", "Description"))
        item = self.userDataTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CreateSnapshotWindow", "Key"))
        item = self.userDataTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CreateSnapshotWindow", "Value"))
        self.createPushButton.setText(_translate("CreateSnapshotWindow", "Create"))
        self.pushButton_2.setText(_translate("CreateSnapshotWindow", "Cancel"))
        self.readOnlyCheckBox.setText(_translate("CreateSnapshotWindow", "Read only"))
